image: viaduck/ci:android

variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - export ANDROID_HOME=/android/sdk
  - export PATH=$PATH:$ANDROID_HOME/platform-tools
  - export GRADLE_USER_HOME=/gradle-cache/.gradle

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew assembleDebug --info
  artifacts:
    paths:
    - app/build/outputs/
